
spring:
  h2:
    console:
      enabled:  true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb #Change to Docker/Container
  security:
    user:
      name: sa
  jackson:
    serialization:
      indent_output: true


server:
  error:
    whitelabel:
      enabled: false
    path: /error
